/*
 MIT or GPL-2.0
 @fileOverview Favico animations
 @author Miroslav Magda, http://blog.ejci.net
 @version 0.3.10
*/
(function(){var v=function(A){var B,v,x,C;function F(a){if(a.paused||a.ended||w)return!1;try{b.clearRect(0,0,f,h),b.drawImage(a,0,0,f,h)}catch(e){}J=setTimeout(function(){F(a)},g.duration);y.setIcon(n)}function G(a){a=a.replace(/^#?([a-f\d])([a-f\d])([a-f\d])$/i,function(a,c,d,b){return c+c+d+d+b+b});return(a=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(a))?{r:parseInt(a[1],16),g:parseInt(a[2],16),b:parseInt(a[3],16)}:!1}function K(a,e){var c={},b;for(b in a)c[b]=a[b];for(b in e)c[b]=e[b];return c}
A=A?A:{};var I={bgColor:"#d00",textColor:"#fff",fontFamily:"sans-serif",fontStyle:"bold",type:"circle",position:"down",animation:"slide",elementId:!1,dataUrl:!1,win:window},c,p,h,f,n,b,k,u,D,E,q,w,L,J,m;C=x=v=B=void 0;B="undefined"!=typeof InstallTrigger;v=!!window.chrome;x=!!window.opera||0<=navigator.userAgent.indexOf("Opera");Object.prototype.toString.call(window.HTMLElement).indexOf("Constructor");C=v||B||x;var r=[];q=function(){};u=w=!1;var t={ready:function(){u=!0;t.reset();q()},reset:function(){u&&
(r=[],E=D=!1,b.clearRect(0,0,f,h),b.drawImage(k,0,0,f,h),y.setIcon(n),window.clearTimeout(L),window.clearTimeout(J))},start:function(){if(u&&!E&&0<r.length){E=!0;var a=function(){"type animation bgColor textColor fontFamily fontStyle".split(" ").forEach(function(a){a in r[0].options&&(c[a]=r[0].options[a])});g.run(r[0].options,function(){D=r[0];E=!1;0<r.length&&(r.shift(),t.start())},!1)};D?g.run(D.options,function(){a()},!0):a()}}},z={},M=function(a){a.n="number"===typeof a.n?Math.abs(a.n|0):a.n;
a.x*=f;a.y*=h;a.w*=f;a.h*=h;a.len=(""+a.n).length;return a};z.circle=function(a){a=M(a);var e=!1;2===a.len?(a.x-=.4*a.w,a.w*=1.4,e=!0):3<=a.len&&(a.x-=.65*a.w,a.w*=1.65,e=!0);b.clearRect(0,0,f,h);b.drawImage(k,0,0,f,h);b.beginPath();b.font=c.fontStyle+" "+Math.floor(a.h*(99<a.n?.85:1))+"px "+c.fontFamily;b.textAlign="center";e?(b.moveTo(a.x+a.w/2,a.y),b.lineTo(a.x+a.w-a.h/2,a.y),b.quadraticCurveTo(a.x+a.w,a.y,a.x+a.w,a.y+a.h/2),b.lineTo(a.x+a.w,a.y+a.h-a.h/2),b.quadraticCurveTo(a.x+a.w,a.y+a.h,a.x+
a.w-a.h/2,a.y+a.h),b.lineTo(a.x+a.h/2,a.y+a.h),b.quadraticCurveTo(a.x,a.y+a.h,a.x,a.y+a.h-a.h/2),b.lineTo(a.x,a.y+a.h/2),b.quadraticCurveTo(a.x,a.y,a.x+a.h/2,a.y)):b.arc(a.x+a.w/2,a.y+a.h/2,a.h/2,0,2*Math.PI);b.fillStyle="rgba("+c.bgColor.r+","+c.bgColor.g+","+c.bgColor.b+","+a.o+")";b.fill();b.closePath();b.beginPath();b.stroke();b.fillStyle="rgba("+c.textColor.r+","+c.textColor.g+","+c.textColor.b+","+a.o+")";"number"===typeof a.n&&999<a.n?b.fillText((9999<a.n?9:Math.floor(a.n/1E3))+"k+",Math.floor(a.x+
a.w/2),Math.floor(a.y+a.h-.2*a.h)):b.fillText(a.n,Math.floor(a.x+a.w/2),Math.floor(a.y+a.h-.15*a.h));b.closePath()};z.rectangle=function(a){a=M(a);2===a.len?(a.x-=.4*a.w,a.w*=1.4):3<=a.len&&(a.x-=.65*a.w,a.w*=1.65);b.clearRect(0,0,f,h);b.drawImage(k,0,0,f,h);b.beginPath();b.font=c.fontStyle+" "+Math.floor(a.h*(99<a.n?.9:1))+"px "+c.fontFamily;b.textAlign="center";b.fillStyle="rgba("+c.bgColor.r+","+c.bgColor.g+","+c.bgColor.b+","+a.o+")";b.fillRect(a.x,a.y,a.w,a.h);b.fillStyle="rgba("+c.textColor.r+
","+c.textColor.g+","+c.textColor.b+","+a.o+")";"number"===typeof a.n&&999<a.n?b.fillText((9999<a.n?9:Math.floor(a.n/1E3))+"k+",Math.floor(a.x+a.w/2),Math.floor(a.y+a.h-.2*a.h)):b.fillText(a.n,Math.floor(a.x+a.w/2),Math.floor(a.y+a.h-.15*a.h));b.closePath()};var y={getIcon:function(){var a=!1;if(c.element)a=c.element;else if(c.elementId)a=m.getElementById(c.elementId),a.setAttribute("href",a.getAttribute("src"));else{a:{for(var a=m.getElementsByTagName("head")[0].getElementsByTagName("link"),e=a.length-
1;0<=e;e--)if(/(^|\s)icon(\s|$)/i.test(a[e].getAttribute("rel"))){a=a[e];break a}a=!1}!1===a&&(a=m.createElement("link"),a.setAttribute("rel","icon"),m.getElementsByTagName("head")[0].appendChild(a))}a.setAttribute("type","image/png");return a},setIcon:function(a){a=a.toDataURL("image/png");c.dataUrl&&c.dataUrl(a);if(c.element)c.element.setAttribute("href",a),c.element.setAttribute("src",a);else if(c.elementId){var e=m.getElementById(c.elementId);e.setAttribute("href",a);e.setAttribute("src",a)}else B||
x?(e=p,p=m.createElement("link"),x&&p.setAttribute("rel","icon"),p.setAttribute("rel","icon"),p.setAttribute("type","image/png"),m.getElementsByTagName("head")[0].appendChild(p),p.setAttribute("href",a),e.parentNode&&e.parentNode.removeChild(e)):p.setAttribute("href",a)}},g={duration:40,types:{}};g.types.fade=[{x:.4,y:.4,w:.6,h:.6,o:0},{x:.4,y:.4,w:.6,h:.6,o:.1},{x:.4,y:.4,w:.6,h:.6,o:.2},{x:.4,y:.4,w:.6,h:.6,o:.3},{x:.4,y:.4,w:.6,h:.6,o:.4},{x:.4,y:.4,w:.6,h:.6,o:.5},{x:.4,y:.4,w:.6,h:.6,o:.6},{x:.4,
y:.4,w:.6,h:.6,o:.7},{x:.4,y:.4,w:.6,h:.6,o:.8},{x:.4,y:.4,w:.6,h:.6,o:.9},{x:.4,y:.4,w:.6,h:.6,o:1}];g.types.none=[{x:.4,y:.4,w:.6,h:.6,o:1}];g.types.pop=[{x:1,y:1,w:0,h:0,o:1},{x:.9,y:.9,w:.1,h:.1,o:1},{x:.8,y:.8,w:.2,h:.2,o:1},{x:.7,y:.7,w:.3,h:.3,o:1},{x:.6,y:.6,w:.4,h:.4,o:1},{x:.5,y:.5,w:.5,h:.5,o:1},{x:.4,y:.4,w:.6,h:.6,o:1}];g.types.popFade=[{x:.75,y:.75,w:0,h:0,o:0},{x:.65,y:.65,w:.1,h:.1,o:.2},{x:.6,y:.6,w:.2,h:.2,o:.4},{x:.55,y:.55,w:.3,h:.3,o:.6},{x:.5,y:.5,w:.4,h:.4,o:.8},{x:.45,y:.45,
w:.5,h:.5,o:.9},{x:.4,y:.4,w:.6,h:.6,o:1}];g.types.slide=[{x:.4,y:1,w:.6,h:.6,o:1},{x:.4,y:.9,w:.6,h:.6,o:1},{x:.4,y:.9,w:.6,h:.6,o:1},{x:.4,y:.8,w:.6,h:.6,o:1},{x:.4,y:.7,w:.6,h:.6,o:1},{x:.4,y:.6,w:.6,h:.6,o:1},{x:.4,y:.5,w:.6,h:.6,o:1},{x:.4,y:.4,w:.6,h:.6,o:1}];g.run=function(a,e,b,d){var f=g.types[m.hidden||m.msHidden||m.webkitHidden||m.mozHidden?"none":c.animation];d=!0===b?"undefined"!==typeof d?d:f.length-1:"undefined"!==typeof d?d:0;e=e?e:function(){};d<f.length&&0<=d?(z[c.type](K(a,f[d])),
L=setTimeout(function(){d=b?d-1:d+1;g.run(a,e,b,d)},g.duration),y.setIcon(n)):e()};(function(){c=K(I,A);c.bgColor=G(c.bgColor);c.textColor=G(c.textColor);c.position=c.position.toLowerCase();c.animation=g.types[""+c.animation]?c.animation:I.animation;m=c.win.document;var a=-1<c.position.indexOf("up"),e=-1<c.position.indexOf("left");if(a||e)for(var H in g.types)for(var d=0;d<g.types[H].length;d++){var l=g.types[H][d];a&&(l.y=.6>l.y?l.y-.4:l.y-2*l.y+(1-l.w));e&&(l.x=.6>l.x?l.x-.4:l.x-2*l.x+(1-l.h));
g.types[H][d]=l}c.type=z[""+c.type]?c.type:I.type;p=y.getIcon();n=document.createElement("canvas");k=document.createElement("img");p.hasAttribute("href")?(k.setAttribute("crossOrigin","anonymous"),k.onload=function(){h=0<k.height?k.height:32;f=0<k.width?k.width:32;n.height=h;n.width=f;b=n.getContext("2d");t.ready()},k.setAttribute("src",p.getAttribute("href"))):(k.onload=function(){f=h=32;k.height=h;k.width=f;n.height=h;n.width=f;b=n.getContext("2d");t.ready()},k.setAttribute("src",""))})();return{badge:function(a,
b){b=("string"===typeof b?{animation:b}:b)||{};q=function(){try{if("number"===typeof a?0<a:""!==a){var c={type:"badge",options:{n:a}};"animation"in b&&g.types[""+b.animation]&&(c.options.animation=""+b.animation);"type"in b&&z[""+b.type]&&(c.options.type=""+b.type);["bgColor","textColor"].forEach(function(a){a in b&&(c.options[a]=G(b[a]))});["fontStyle","fontFamily"].forEach(function(a){a in b&&(c.options[a]=b[a])});r.push(c);if(100<r.length)throw Error("Too many badges requests in queue.");t.start()}else t.reset()}catch(d){throw Error("Error setting badge. Message: "+
d.message);}};u&&q()},video:function(a){q=function(){try{"stop"===a?(w=!0,t.reset(),w=!1):a.addEventListener("play",function(){F(this)},!1)}catch(b){throw Error("Error setting video. Message: "+b.message);}};u&&q()},image:function(a){q=function(){try{var c=a.width,g=a.height,d=document.createElement("img"),l=c/f<g/h?c/f:g/h;d.setAttribute("crossOrigin","anonymous");d.onload=function(){b.clearRect(0,0,f,h);b.drawImage(d,0,0,f,h);y.setIcon(n)};d.setAttribute("src",a.getAttribute("src"));d.height=g/
l;d.width=c/l}catch(k){throw Error("Error setting image. Message: "+k.message);}};u&&q()},webcam:function(a){window.URL&&window.URL.createObjectURL||(window.URL=window.URL||{},window.URL.createObjectURL=function(a){return a});if(C){var b=!1;navigator.getUserMedia=navigator.getUserMedia||navigator.oGetUserMedia||navigator.msGetUserMedia||navigator.mozGetUserMedia||navigator.webkitGetUserMedia;q=function(){try{"stop"===a?(w=!0,t.reset(),w=!1):(b=document.createElement("video"),b.width=f,b.height=h,
navigator.getUserMedia({video:!0,audio:!1},function(a){b.src=URL.createObjectURL(a);b.play();F(b)},function(){}))}catch(c){throw Error("Error setting webcam. Message: "+c.message);}};u&&q()}},reset:t.reset,browser:{supported:C}}};"undefined"!==typeof define&&define.amd?define([],function(){return v}):"undefined"!==typeof module&&module.exports?module.exports=v:this.Favico=v})();
